#@TYPE: Machine
#@NAME: EcoG ARMv7 Emulated Machine
#@DESCRIPTION: Machine configuration for testing ocpppy on ARMv7 via QEMU

# Base it on the standard QEMU ARM configuration
require conf/machine/qemuarm.conf

DEFAULTTUNE = "armv7athf-neon"

